#!/usr/bin/env bash

#******************************************************************************
# Copyright 2015 the original author or authors.                              *
#                                                                             *
# Licensed under the Apache License, Version 2.0 (the "License");             *
# you may not use this file except in compliance with the License.            *
# You may obtain a copy of the License at                                     *
#                                                                             *
# http://www.apache.org/licenses/LICENSE-2.0                                  *
#                                                                             *
# Unless required by applicable law or agreed to in writing, software         *
# distributed under the License is distributed on an "AS IS" BASIS,           *
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    *
# See the License for the specific language governing permissions and         *
# limitations under the License.                                              *
#******************************************************************************/

CWD=$(pwd)
source $CWD/setenv

## Set File System Layout
mkdir -p /usr/java/
chown -R root:root /usr/java
chmod -R 755 /usr/java
ln -s /usr/java/jdk1.8.0_45 /usr/java/orajava8

mkdir -p /prj/opennms
